name: CI Workflow

on:
  pull_request:
    branches:
      - "main"
permissions:
  contents: read

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Create test env
        shell: bash -l {0}
        run: |
          pip install pylint mccabe
      - name: Run Pylint
        shell: bash -l {0}
        run: |
          pylint --recursive=y --disable=all --fail-under=10 --enable=too-many-statements,too-many-nested-blocks src/eolab/georastertools/
      - name: Run McCabe Complexity Check
        shell: bash -l {0}
        run: |
          ./continuous_integration/scripts/check_mccabe_complexity.sh 25 src/eolab/georastertools/

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: '3.12'
        auto-activate-base: false
    - name: Create test env
      shell: bash -l {0}
      run: |
        conda create -n test_env python=3.12 libgdal=3.13 -c conda-forge -c defaults -y
        conda activate test_env
        PIP_NO_BINARY=rasterio pip install .
    - name: test
      shell: bash -l {0}
      run: |
        conda activate test_env
        PYTHONPATH=src pytest --compare --durations=0 --cov=src/eolab/georastertools/ --cov-report=xml:.ci-reports-georastertools/coverage_georastertools.xml --cov-report html:cov_html_georastertools --cov-report=term --junitxml=pytest-results-georastertools.xml
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report-georastertools
        path: |
          .ci-reports-georastertools/
          cov_html_georastertools/
          pytest-results-georastertools.xml
